### ISSUE TITLE
Extra newline gets lost during parsing

### ISSUE THREAD

**Issue by daria-kopaliani** [henrinormak/NORMarkdownParser#1]
Thank you for the great parser, but I think that the final `NSAttributedString` is missing one "\n". For instance (from your example:)

```
NSString *markdown = @"First Line.\n\nThis is a *markdown* string, _boom!_ -> [GitHub](https://github.com/henrinormak/NORMarkdownParser)";
NORMarkdownParser *parser = [[NORMarkdownParser alloc] initWithExtensions:NORMarkdownAutolink | NORMarkdownHighlight | NORMarkdownStrikethrough | NORMarkdownUnderline];
NSString *stripped = nil;
NSAttributedString *parsed = [parser attributedStringFromMarkdown:markdown strippedString:&stripped];
```

Will return

First Line.
This is a markdown string, boom! -> GitHub

One "\n" is lost.

**Comment by henrinormak** [comment]
Interesting, thanks for creating an issue, I'll investigate whether this is from the Obj-C wrapper or caused by the underlying Hoedown library.

**Comment by henrinormak** [comment]
After some investigation I concluded that this is expected by the [Markdown spec](http://daringfireball.net/projects/markdown/syntax#p). To create a forced new line, end a paragraph with "  " (double space). In essence the result you are looking for is obtainable by using a different looking input, roughly something like this

```
NSString *markdown = @"First Line.  \nThis is a *markdown* string, _boom!_ -> [GitHub](https://github.com/henrinormak/NORMarkdownParser)";
```
